routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');

Route::middleware(['auth'])->group(function(){
    Route::get('/home', 'HomeController@index')->name('home');
});

//AUTENTICACION
Auth::routes();

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.request');

//PRODUCTOS
Route::get('products/{product}', 'ProductController@show');


//CATEGORIAS
Route::get('categories', 'CategoryController@index')->name('categories');
Route::get('categories/{category}', 'CategoryController@show');


//CONTACTO
Route::get('contact', 'MessageController@index')->name('contact');
Route::get('contact/{product}', 'MessageController@index_product');
Route::post('contact', 'MessageController@send')->name('contact.send');

//BUSCAR
Route::get('search', 'SearchController@search');


//
Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->group(function(){


    Route::get('/products', 'ProductController@index')->name('list_products'); //listar
    Route::get('/products/create', 'ProductController@create')->name('create_product');
    Route::post('/products', 'ProductController@store')->name('product_store'); //almacenar producto
    Route::get('/products/edit/{product}', 'ProductController@edit'); //editar producto
    Route::post('/products/update/{product}', 'ProductController@update'); //guardar cambios producto
    Route::delete('/products/{product}', 'ProductController@delete'); //eliminar producto

    Route::get('/products/images/{id}', 'ImageController@index'); //listar imagenes
    Route::post('/products/images/{id}', 'ImageController@store'); //almacenar imagenes
    Route::delete('/products/images/{image}', 'ImageController@delete'); //eliminar imagen
    Route::get('/products/images/select/{id}/{image_id}', 'ImageController@destacar_imagen'); //destacar imagen

    Route::get('/categories', 'CategoryController@index')->name('list_categories'); //listar categorias
    Route::get('/categories/create', 'CategoryController@create')->name('create_category'); //formulario de registro de categorias
    Route::post('/categories', 'CategoryController@store')->name('category_store');; //almacenar categoria
    Route::get('/categories/edit/{category}', 'CategoryController@edit'); //editar categoria
    Route::post('/categories/update/{category}', 'CategoryController@update'); //guardar cambios categoria
    Route::delete('/categories/{category}', 'CategoryController@delete'); //eliminar categoria

});

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Intervention\Image\ImageManager;
use File;

class Image extends Model
{
    protected $fillable  = ['product_id','image', 'thumb_image'];

    public function product(){
        return $this->belongsTo(Product::class);
    }

    protected static function boot(){
        parent::boot();
        static::deleting(function(Image $image){
            if(substr($image->image, 0, 4) !== 'http'){
                $fullPath = public_path().'/images/products/'.$image->image;
                $fullPath_thumb = public_path().'/images/products/thumbnails/'.$image->thumb_image;
                File::delete($fullPath);
                File::delete($fullPath_thumb);
            }
        });

    }

    public function destacar($product_id){
        Image::where('product_id', $product_id)->update([
            'featured' => false,
        ]);
        $this->featured = true;
        $this->save();
    }

    public function getUrlAttribute(){
        if(substr($this->image, 0, 4) === "http"){
            return $this->image;
        }
        return asset('/images/products/'.$this->image);
    }

    public function getThumbnailUrlAttribute(){
        if(substr($this->image, 0, 4) === "http"){
            return $this->image;
        }
        return asset('/images/products/thumbnails/'.$this->thumb_image);
    }


}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

    protected $fillable = ['name', 'description', 'long_description', 'price', 'user_id', 'category_id'];

    public static $messages = [
        'name.required' => 'El campo nombre es obligatorio',
        'name.min' => 'El campo nombre debe contener 3 caracteres como mínimo',
        'description.required' => 'El campo descripcion es obligatorio',
        'price.required' => 'El campo del precio es obligatorio',
        'price.numeric' => 'El campo del precio debe ser numérico',
        'price.min' => 'El campo del precio debe ser un numero positivo',
    ];

    public static $rules = [
        'name' => 'required|min:3',
        'description' => 'required',
        'price' => 'required|numeric|min:0'
    ];

    public function category(){
        return $this->belongsTo(Category::class);
    }

    public function product_images(){
        return $this->hasMany(Image::class);
    }

    //ACCESSOR
    public function getFeaturedImageUrlAttribute(){
        $featuredImage = $this->product_images()->where('featured', true)->first();
        if(!$featuredImage){
            $featuredImage = $this->product_images()->first();
            if(!$featuredImage){
                return 'images/products/default.png';
            }
        }
        return $featuredImage->url;
    }
    public function getCategoryNameAttribute(){

        if(!isset($this->category)){
            return "General";
        }
        return $this->category->name;
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;
use App\Product;
use Illuminate\Support\Facades\DB;
use File;


class ProductController extends Controller
{
    public function index(){
        $products = Product::orderBy('created_at', 'desc')->paginate(12);
        return view('admin.products.index')->with(compact('products'));
    }
    public function create(){
        $categories = Category::all();
        return view('admin.products.create')->with(compact('categories'));
    }
    public function store(Request $request){
        //dd($request->input('description'));
        $this->validate($request, Product::$rules);

        $success = true;
        DB::beginTransaction();
        try{
            $product = Product::create([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'long_description' => $request->input('long_description'),
                'price' => $request->input('price'),
                'category_id' => $request->input('category'),
                'user_id' => auth()->user()->id
            ]);
        } catch (\Exception $exception){
            $success = $exception->getMessage();
            DB::rollBack();
        }
        if($success === true){
            DB::commit();
            session()->flash('message', ['type' => 'success', 'text'=>'articulo registrado correctamente']);
            return redirect('admin/products/images/'.$product->id);
        }
        else{
            session()->flash('message', ['type' => 'danger', 'text'=>$success]);
            return back();
        }

    }

    public function edit(Product $product){
        $images = $product->images;
        $categories = Category::all();
        return view('admin.products.edit')->with(compact('product', 'images', 'categories')); //formulario de registro
    }

    public function update(Product $product, Request $request){
        //dd($request);
        $this->validate($request, Product::$rules, Product::$messages);
        $success = true;

        DB::beginTransaction();
        try{
            $product->update([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'long_description' => $request->input('long_description'),
                'price' => $request->input('price'),
                'category_id' => $request->input('category'),
            ]);
        } catch(\Exception $exception){
            $success = $exception->getMessage();
            DB::rollBack();
        }
        if($success === true){
            DB::commit();
            session()->flash('message', ['type' => 'success', 'text'=>'cambios guardados correctamente']);
        }
        else{
            session()->flash('message', ['type' => 'danger', 'text'=>$success]);
        }
        return back();
    }

    public function delete(Product $product){
        $success = true;
        $product_images = $product->product_images;
        foreach($product_images as $product_image){
            $product_image->delete();
        }
        DB::beginTransaction();
        try{
            $product->delete();
        } catch(\Exception $exception){
            $success = $exception->getMessage();
            DB::rollBack();
        }
        if($success === true){
            DB::commit();
            return response()->json(['type' => 'success', 'text' => 'Producto #'.$product->id.' eliminado correctamente']);
            //session()->flash('message', ['type' => 'success', 'text'=>'Producto eliminado correctamente']);
        }
        else{
            return response()->json(['type' => 'warning', 'text' => $success]);
            //session()->flash('message', ['type' => 'danger', 'text'=>$success]);
        }
        //return back();
    }



}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use Illuminate\Http\Request;
use Intervention\Image\ImageManager;

class ProductController extends Controller
{
    public function products_category(Category $category){
        $products = $category->products;
        return view('products.index')->with(compact('products'));
    }
    public function show(Product $product){
        $images = $product->product_images;
        $intervention = new ImageManager(['driver'=>'imagick']);
        return view('products.show')->with(compact('product','images', 'intervention'));
    }
}

resources/views/products/index.blade.php
@extends('layouts.app')

@section('nav-class', 'navbar navbar-expand-lg bg-primary fixed-top')
@section('transparency', '')

@section('scripts')
    <script type="text/javascript">
        var scroll = new SmoothScroll('a[href*="#_"]');


    </script>
@endsection
@section('styles')
    <style>
        .img-container {
            height: 200px;
            max-height: 200px;
            overflow: hidden;
            position: relative;
        }
        .img-container > .crop {
            position:absolute;
            left: -100%;
            right: -100%;
            top: -100%;
            bottom: -100%;
            margin: auto;
            min-height: 100%;
            min-width: 100%;
            transition:all .5s ease-in-out;
        }
        .img-container:hover > .crop{
            -webkit-transform:scale(1.3);
            transform: scale(1.3);
            transition:all .5s ease-in-out;
        }

    </style>
@endsection

<!-- End Navbar -->
@section('content')
    {{--<div class="page-header page-header-ultra-small">
        <div class="page-header-image" data-parallax="true" style="background-image: url('{{ asset('images/portada.jpg') }}');">
        </div>
        <div class="content-center">
            <div class="container">
                <h1 class="title" style="font-size:5vh">Decoración con madera</h1>
                <div class="text-center">
                    <a href="#pablo" class="btn btn-primary btn-icon btn-round">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="#pablo" class="btn btn-primary btn-icon btn-round">
                        <i class="fab fa-facebook"></i>
                    </a>
                    <a href="#pablo" class="btn btn-primary btn-icon btn-round">
                        <i class="fab fa-google-plus"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>--}}

    <div class="section section-team text-center" style="background-color:  #feecd3">
        <div class="container">
            <h2 class="title">{{ __('Categorias') }}</h2>
            <div class="team">
                <div class="row">
                    @foreach ($categories as $category)
                        @include('partials.categories.category_card')
                    @endforeach
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('nav-class', 'navbar navbar-expand-lg bg-primary fixed-top')
@section('transparency', '')

@section('scripts')
    <script type="text/javascript">
        var scroll = new SmoothScroll('a[href*="#_"]');
    </script>
    <script type="text/javascript" src="{{ asset('js/lightgallery-all.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/picturefill/2.3.1/picturefill.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#lightgallery").lightGallery({
                getCaptionFromTitleOrAlt: false,
                download: false,
            });
            $('.img-gallery').mouseover(function () {
                $('#main-img').attr('src',$(this).attr('data-src'))
            })
        })

    </script>
@endsection
@section('styles')
    <link type="text/css" rel="stylesheet" href="{{ asset('css/lightgallery.css') }}" />
@endsection

<!-- End Navbar -->
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 p-3 rounded shadow" style="margin-bottom:100px; margin-top: 90px; background-color:  #feecd3;">
                <h2 class="title text-center">{{ $product->name }}</h2>
                <div class="row justify-content-center">
                    <div class="col-md-5">
                        <div class="col-12 mb-4 px-0">
                            <img id="main-img" class="img-fluid rounded w-100" src="{{ $product->featured_image_url }}" alt="">
                        </div>
                        <div class="col-12">
                            <div class="row" id="lightgallery">
                                @foreach ($images as $image)
                                    <div class="col-3 px-0 img-gallery" data-src="{{ $image->url }}" data-responsive="{{ $image->url }} 757">
                                        <a  href="">
                                            <img class="img-thumbnail rounded" src="{{ $image->thumbnail_url }}" alt="{{ 'image_'.$product->name.'_'.$image->id }}">
                                        </a>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                    <div class="col-md-7 text-left mt-3">
                        <p>{{ $product->long_description }}</p>
                        <p><a class="font-weight-bold text-warning" href="{{ url('contact/'.$product->id) }}">{{ __('Consulta sobre este proyecto') }}</a></p>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <a href="{{ back()->getTargetUrl() }}" class="btn btn-warning">{{ __('Volver') }}</a>
                </div>
            </div>
        </div>
    </div>

@endsection