routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');

Route::middleware(['auth'])->group(function(){
    Route::get('/home', 'HomeController@index')->name('home');
});

//AUTENTICACION
Auth::routes();

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.request');

//PRODUCTOS
Route::get('products/{product}', 'ProductController@show');


//CATEGORIAS
Route::get('categories', 'CategoryController@index')->name('categories');
Route::get('categories/{category}', 'CategoryController@show');


//CONTACTO
Route::get('contact', 'MessageController@index')->name('contact');
Route::get('contact/{product}', 'MessageController@index_product');
Route::post('contact', 'MessageController@send')->name('contact.send');

//BUSCAR
Route::get('search', 'SearchController@search');


//
Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->group(function(){


    Route::get('/products', 'ProductController@index')->name('list_products'); //listar
    Route::get('/products/create', 'ProductController@create')->name('create_product');
    Route::post('/products', 'ProductController@store')->name('product_store'); //almacenar producto
    Route::get('/products/edit/{product}', 'ProductController@edit'); //editar producto
    Route::post('/products/update/{product}', 'ProductController@update'); //guardar cambios producto
    Route::delete('/products/{product}', 'ProductController@delete'); //eliminar producto

    Route::get('/products/images/{id}', 'ImageController@index'); //listar imagenes
    Route::post('/products/images/{id}', 'ImageController@store'); //almacenar imagenes
    Route::delete('/products/images/{image}', 'ImageController@delete'); //eliminar imagen
    Route::get('/products/images/select/{id}/{image_id}', 'ImageController@destacar_imagen'); //destacar imagen

    Route::get('/categories', 'CategoryController@index')->name('list_categories'); //listar categorias
    Route::get('/categories/create', 'CategoryController@create')->name('create_category'); //formulario de registro de categorias
    Route::post('/categories', 'CategoryController@store')->name('category_store');; //almacenar categoria
    Route::get('/categories/edit/{category}', 'CategoryController@edit'); //editar categoria
    Route::post('/categories/update/{category}', 'CategoryController@update'); //guardar cambios categoria
    Route::delete('/categories/{category}', 'CategoryController@delete'); //eliminar categoria

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use File;


class Category extends Model
{
    protected $fillable = ['name', 'description', 'image'];

    public static $rules = [
        'name' => 'required|min:3',
    ];

    protected static function boot(){
        parent::boot();
        static::deleting(function(Category $category){
            if(substr($category->image, 0, 4) !== 'http'){
                $fullPath = public_path().'/images/categories/'.$category->image;
                File::delete($fullPath);
            }
        });
    }

    public function products(){
        return $this->hasMany(Product::class);
    }
    public function getUrlImageAttribute(){

        if($this->image == NULL){
            return '/images/categories/default.png';
        }
        else{
            if (substr($this->image, 0, 4) === "http") {
                return $this->image;
            }
        }
        return asset('/images/categories/'.$this->image);
    }

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;
use App\Product;
use Illuminate\Support\Facades\DB;
use File;
use Intervention\Image\ImageManager;

class CategoryController extends Controller
{
    public function index(){
        $categories = Category::orderBy('created_at','DESC')->get();
        return view('admin.categories.index')->with(compact('categories'));
    }
    public function create(){
        return view('admin.categories.create');
    }
    public function store(Request $request){

        //dd($request->all()); //muestra todos los datos request
        $success = true;
        $this->validate($request, Category::$rules);

        DB::beginTransaction();
        try{
            if($request->hasFile('image')){
                $file = $request->file('image');
                $path = public_path().'/images/categories/temp';
                $fileName = uniqid().$file->getClientOriginalName();
                if($file->move($path, $fileName)){
                    $intervention = new ImageManager(['driver'=>'gd']);
                    $img = $intervention->make(public_path().'/images/categories/temp/'.$fileName)->fit(524, 150);
                    $img->save(public_path().'/images/categories/'.$fileName);
                    File::delete(public_path().'/images/categories/temp/'.$fileName);
                }
            }
            $category = Category::create([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'image' => $fileName
            ]);
        } catch (\Exception $exception){
            $success = $exception->getMessage();
            DB::rollBack();
        }
        if($success === true){
            DB::commit();
            session()->flash('message', ['type' => 'success', 'text'=>'categoria registrada correctamente']);
            return redirect('admin/categories');
        }
        else{
            session()->flash('message', ['type' => 'danger', 'text'=>$success]);
            return back();
        }
    }
    public function edit(Category $category){
        return view('admin.categories.edit')->with(compact('category')); //formulario de edicion de categorias
    }
    public function update(Request $request, Category $category){

        $success = true;
        $this->validate($request, Category::$rules);

        DB::beginTransaction();
        try{
            if($request->hasFile('image')){

                $file = $request->file('image');
                $path = public_path().'/images/categories/temp';
                File::delete(public_path().'/images/categories/'.$category->image);

                $fileName = uniqid().$file->getClientOriginalName();
                Category::find($category->id)->update([
                    'name' => $request->input('name'),
                    'description' => $request->input('description'),
                    'image' => $fileName
                ]);
                if($file->move($path, $fileName)){
                    $intervention = new ImageManager(['driver'=>'gd']);
                    $img = $intervention->make(public_path().'/images/categories/temp/'.$fileName)->fit(524, 150);
                    $img->save(public_path().'/images/categories/'.$fileName);
                    File::delete(public_path().'/images/categories/temp/'.$fileName);
                }
            }
            else{
                $category->update([
                    'name' => $request->input('name'),
                    'description' => $request->input('description'),
                ]);
            }
        }catch(\Exception $exception){
            $success = $exception->getMessage();
            DB::rollBack();
        }
        if($success === true){

            DB::commit();
            session()->flash('message', ['type' => 'success', 'text'=>'categoria actualizada correctamente']);
        }
        else{
            session()->flash('message', ['type' => 'danger', 'text'=>$success]);
        }
        return back();
    }

    public function delete(Category $category){
        $success = true;
        DB::beginTransaction();
        try{
            $category->delete();
        }
        catch (\Exception $exception){
            $success = $exception->getMessage();
            DB::rollBack();
        }

        if($success === true){
            DB::commit();
            session()->flash('message', ['type' => 'success', 'text'=>'categoria eliminada correctamente']);
        }
        else{
            session()->flash('message', ['type' => 'danger', 'text'=>$success]);
        }
        return back();
    }



}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    public function index(){
        $categories = Category::all();
        return view('categories.index')->with(compact('categories'));
    }

    public function show(Category $category){
        $products = $category->products()->paginate(6);
        $categories = Category::all();
        return view('categories.show')->with(compact('products', 'category', 'categories'));
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('nav-class', 'navbar navbar-expand-lg bg-primary fixed-top')
@section('transparency', '')

@section('content')
    <div class="section section-team">
        <div class="container">
            <h2 class="title">{{ __('Registrar categoria') }}</h2>
            <div class="team">
                <form class="form" method="post" action="{{ route('category_store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-lg-6 col-md-12">
                            <div class="form-group">
                                <label for="name" class="mr-auto">{{ __('Nombre') }}</label>
                                <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}">
                                @if ($errors->has('name'))
                                    <span class="text-danger" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="description" class="mr-auto">{{ __('Descripción') }}</label>
                                <input value="{{ old('description') }}" type="text" class="form-control" id="description" name="description">
                                @if ($errors->has('description'))
                                    <span class="text-danger" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-12">
                            <div class="form-group">
                                <label for="description" class="mr-auto">{{ __('Imagen') }}</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="image" name="image">
                                        <label class="custom-file-label" for="image">Buscar imagen</label>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                        <button type="submit" href="{{ route('list_categories') }}" class="btn btn-warning btn-round btn-lg" type="submit">{{ __('Guardar') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('nav-class', 'navbar navbar-expand-lg bg-primary fixed-top')
@section('transparency', '')

@section('content')
    <div class="section section-team">
        <div class="container">
            @include('partials.messages.general_messages')
            <h2 class="title">{{ __('Editar categoria').": ".$category->name }}</h2>
            <div class="team">
                <form class="form" method="post" action="{{ url('/admin/categories/update/'.$category->id) }}" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-lg-6 col-md-12">
                            <div class="form-group">
                                <label for="name" class="mr-auto">{{ __('Nombre') }}</label>
                                <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $category->name) }}">
                                @if ($errors->has('name'))
                                    <span class="text-danger" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="description" class="mr-auto">{{ __('Descripción') }}</label>
                                <input value="{{ old('description', $category->description) }}" type="text" class="form-control" id="description" name="description">
                                @if ($errors->has('description'))
                                    <span class="text-danger" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-12">
                            <img src="{{ $category->url_image }}" alt="">
                            <div class="form-group">
                                <label for="description" class="mr-auto">{{ __('Imagen') }}</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="image" name="image">
                                        <label class="custom-file-label" for="image">Buscar imagen</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                        <button type="submit" href="{{ route('list_categories') }}" class="btn btn-warning btn-round btn-lg" type="submit">{{ __('Guardar') }}</button>
                        <a href="{{ route('list_categories') }}" class="btn btn-warning btn-round btn-lg">Volver</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')

@section('nav-class', 'navbar navbar-expand-lg bg-primary fixed-top')
@section('transparency', '')

@section('content')
    <div class="section section-team text-center">
        <div class="container">
            @include('partials.messages.general_messages')
            <h2 class="title">{{ __('Categorias') }}</h2>
            <div class="team">
                <div class="row">
                    <a href="{{ route('create_category') }}" class="btn btn-success">
                        {{ __("Registrar nueva categoria") }}
                    </a>
                    <table class="table col-md-12">
                        <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th class="text-center">Imagen</th>
                            <th class="text-left">Nombre</th>
                            <th class="d-none d-sm-table-cell text-left">Descripcion</th>
                            <th class="text-right" style="width:15%">Opciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $category)
                            <tr>
                                <td class="text-center">{{ $category->id }}</td>
                                <td class="text-center"><img src="{{ $category->url_image }}" style="height: 60px; min-width: 144px" alt=""></td>
                                <td class="text-left">{{ $category->name }}</td>
                                <td class="text-left d-none d-sm-table-cell">{{ $category->description }}</td>
                                <td class="td-actions text-right">
                                   {{-- <a href="{{ url('products/'.$product->id) }}" target="_blank" rel="tooltip" title="Detalles" class="btn btn-link px-1 text-info my-0 py-0">
                                        <i class="fa fa-info"></i>
                                    </a> --}}
                                    <a href="{{ url('admin/categories/edit/'.$category->id) }}"  rel="tooltip" title="Editar datos" class="btn btn-link px-1 text-success px-0 my-0 py-0">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <form action="{{ url('admin/categories/'.$category->id) }}" method="post" class="d-inline">
                                    {{ csrf_field() }} <!-- es equivalente a <input type="hidden" name="_token" value="csrf_token" /> -->
                                    {{ method_field('DELETE') }} <!-- es equivalente a <input type="hidden" name="_method" value="DELETE" /> -->
                                        <button type="submit" rel="tooltip" title="Eliminar categoria" class="btn px-1 btn-link text-danger my-0 py-0">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    </form>

                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection